version: '3.7'

services:
  ca-hospital:
    image: hyperledger/fabric-ca:1.5
    container_name: ca.hospitalOrg.example.com
    ports:
      - "7054:7054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hospital
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_GENERATE=true
    volumes:
      - ../organizations/fabric-ca/hospitalOrg:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - ehr-net

networks:
  ehr-net:
