version: 1.2.0

port: 7050
debug: false
crlsizelimit: 512000

tls:
  enabled: true
  clientauth:
    type: noclientcert
    certfiles:

ca:
  name: ca-orderer
  keyfile:
  certfile:
  chainfile:

crl:
  expiry: 24h

registry:
  maxenrollments: -1
  identities:
    - name: admin
      pass: adminpw
      type: client
      affiliation: ""
      attrs:
        hf.Registrar.Roles: "*"
        hf.Registrar.DelegateRoles: "*"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.GenCRL: true
        hf.Registrar.Attributes: "*"
        hf.AffiliationMgr: true

db:
  type: sqlite3
  datasource: fabric-ca-server.db
  tls:
    enabled: false

ldap:
  enabled: false

affiliations:
  orderer:
    - department1
    - department2

signing:
  default:
    usage:
      - digital signature
    expiry: 8760h
  profiles:
    ca:
      usage:
        - cert sign
        - crl sign
      expiry: 43800h
      caconstraint:
        isca: true
        maxpathlen: 0
    tls:
      usage:
        - signing
        - key encipherment
        - server auth
        - client auth
        - key agreement
      expiry: 8760h

csr:
  cn: ca.ordererOrg.example.com
  names:
    - C: BD
      ST: Dhaka
      L: Dhaka
      O: ordererOrg.example.com
      OU: IT
  hosts:
    - localhost
    - ca.ordererOrg.example.com
  ca:
    expiry: 131400h
    pathlength: 1

bccsp:
  default: SW
  sw:
    hash: SHA2
    security: 256
    filekeystore:
      keystore: msp/keystore
