version: '3.7'

volumes:
  orderer.example.com:

networks:
  ehr-net:
    external: true

services:
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/orderer.genesis.block  # new added 
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file    # set it file // old none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=false   # set if false // old true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053 
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.example.com:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/orderer/tls
      - ../config/artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - orderer.example.com:/var/hyperledger/production/orderer
      
    ports:
      - 7050:7050
      # - 7053:7053
      # - 9443:9443
    networks:
      - ehr-net





# version: '3.7'

# volumes:
#   orderer.example.com:

# networks:
#   ehr-net:
#     external: true
# services:
#   orderer.example.com:
#     container_name: orderer.example.com
#     image: hyperledger/fabric-orderer:latest
#     labels:
#       service: hyperledger-fabric
#     environment:
#       - FABRIC_LOGGING_SPEC=INFO
#       - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
#       - ORDERER_GENERAL_LISTENPORT=7050
#       - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
#       - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
#       # enabled TLS
#       - ORDERER_GENERAL_TLS_ENABLED=true
#       - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
#       - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
#       - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
#       - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
#       - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
#       - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
#       - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
#       - ORDERER_CHANNELPARTICIPATION_ENABLED=true
#       - ORDERER_ADMIN_TLS_ENABLED=true
#       - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
#       - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
#       - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
#       - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
#       - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
#       - ORDERER_OPERATIONS_LISTENADDRESS=orderer.example.com:9443
#       - ORDERER_METRICS_PROVIDER=prometheus
#     working_dir: /root
#     command: orderer
#     volumes:
#         - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
#         - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
#         - orderer.example.com:/var/hyperledger/production/orderer
#     ports:
#       - 7050:7050
#       - 7053:7053
#       - 9443:9443
#     networks:
#       - ehr-net